name: Build Core Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache PlatformIO Folders
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          ats-mini-core/.pio
        key: ${{ runner.os }}-platformio-${{ hashFiles('ats-mini-core/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Compile Firmware
      working-directory: ats-mini-core
      run: pio run

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ats-mini-core-firmware
        path: ats-mini-core/.pio/build/esp32s3/firmware.bin
